UPDATE ZAGAR_CURRENCY_RATE
SET ZAGAR_CURRENCY_RATE.VALIDTO = $validFrom
WHERE
    ZAGAR_CURRENCY_RATE.ID IN (
        SELECT ZAGAR_CURRENCY_RATE.ID
        FROM ZAGAR_CURRENCY_RATE
        INNER JOIN OFFICE_CODE_ZAGAR_CURRENCY_RATE ON ZAGAR_CURRENCY_RATE.ID = OFFICE_CODE_ZAGAR_CURRENCY_RATE.ZAGARCURRENCYRATE_ID
        WHERE 
            ZAGAR_CURRENCY_RATE.ZAGARPRODUCTGROUP_CODE = $productGroupCode
            AND OFFICE_CODE_ZAGAR_CURRENCY_RATE.OFFICECODE IN $officeCode
            AND ZAGAR_CURRENCY_RATE.BASESIGNCURRENCYCODE = $baseCurrencySignCode
            AND ZAGAR_CURRENCY_RATE.QUOTEDSIGNCURRENCYCODE = $quotedCurrencySignCode
            AND ZAGAR_CURRENCY_RATE.VALIDTO IS NULL
        ORDER BY VALIDFROM DESC
    )
;
