UPDATE ZAGAR_CURRENCY_RATE
SET ZAGAR_CURRENCY_RATE.EXCHANGERATELIMITTO = $limit
WHERE
    ZAGAR_CURRENCY_RATE.ID IN (SELECT ZAGAR_CURRENCY_RATE.ID
    FROM ZAGAR_CURRENCY_RATE
    INNER JOIN OFFICE_CODE_ZAGAR_CURRENCY_RATE ON OFFICE_CODE_ZAGAR_CURRENCY_RATE.ZAGARPRODUCTGROUP_ID = ZAGAR_CURRENCY_RATE.ID
    WHERE 
        ZAGAR_CURRENCY_RATE.ZAGARPRODUCTGROUP_CODE = $productGroupCode
        AND ZAGAR_CURRENCY_RATE.EXCHANGERATELIMITFROM < $limit
        AND ZAGAR_CURRENCY_RATE.EXCHANGERATELIMITTO IS NULL
        AND OFFICE_CODE_ZAGAR_CURRENCY_RATE.OFFICECODE IN $officeCode
        AND ZAGAR_CURRENCY_RATE.BASESIGNCURRENCYCODE = $baseCurrencySignCode
        AND ZAGAR_CURRENCY_RATE.QUOTEDSIGNCURRENCYCODE = $quotedCurrencySignCode
        AND ZAGAR_CURRENCY_RATE.VALIDFROM = $validFrom
        )
    ORDER BY ZAGAR_CURRENCY_RATE.EXCHANGERATELIMITFROM ASC)
;