SELECT ZAGAR_CURRENCY_RATE.ID IS NOT NULL
FROM ZAGAR_CURRENCY_RATE
INNER JOIN OFFICE_CODE_ZAGAR_CURRENCY_RATE ON ZAGAR_CURRENCY_RATE.ID = OFFICE_CODE_ZAGAR_CURRENCY_RATE.ZAGARCURRENCYRATE_ID
WHERE 
    ZAGAR_CURRENCY_RATE.ZAGARPRODUCTGROUP_CODE = $productGroupCode
    AND ZAGAR_CURRENCY_RATE.EXCHANGERATELIMITFROM = $limit
    AND OFFICE_CODE_ZAGAR_CURRENCY_RATE.OFFICECODE IN $officeCode
    AND ZAGAR_CURRENCY_RATE.BASECURRENCYSIGNCODE = $baseCurrencySignCode
    AND ZAGAR_CURRENCY_RATE.QUOTEDCURRENCYSIGNCODE = $quotedCurrencySignCode
    AND ZAGAR_CURRENCY_RATE.VALIDFROM = $validFrom